# snake/interfaces/render.py
from __future__ import annotations
from typing import Protocol, Optional
from . import Snapshot

class Renderer(Protocol):
    def open(self, grid_w: int, grid_h: int, cfg: RenderConfig) -> None: ...
    def draw(self, snap: Snapshot) -> None: ...
    def tick(self, fps: int) -> None: ...
    def close(self) -> None: ...
    def save_frame(self, snap: Snapshot) -> None: ...
