# snake/viz/snapshot_sink.py
from __future__ import annotations
from typing import Protocol, Optional
from core.interfaces import Snapshot

class SnapshotSink(Protocol):
    def start(self, grid_w: int, grid_h: int) -> None: ...
    def push(self, snap: Snapshot) -> None: ...
    def close(self) -> None: ...
